kind: pipeline
type: docker
name: site-update

clone:
  depth: 1

steps:
- name: update
  image: alpine
  volumes:
  - name: html
    path: /html
  commands:
  - ls -a
  - ls -a /html
  - rm -rf /html/*
  - ls -a /html
  - mv dist /html/
  - ls -a

volumes:
- name: html
  host:
    path: /usr/local/soft/nginx/html/tools