kind: pipeline
type: exec
name: hello

clone:
  disable: true

steps:
- name: greeting
  commands:
  - echo hello world

- name: update
  command:
  - pwd
  - cd /usr/local/soft/nginx/html/tools/
  - pwd
  - git pull
  - echo finish