kind: pipeline
type: docker
name: site-update

clone:
  depth: 1

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello world

- name: update
  image: alpine
  volumes:
  - name: html
    path: /html
  commands:
  - rm -rf /html/*
  - mv dist /html/

volumes:
- name: html
  host:
    path: /usr/local/soft/nginx/html/tools