kind: pipeline
type: docker
name: site-update

clone:
  depth: 1

steps:
- name: update
  pull: if-not-exists
  image: alpine
  volumes:
  - name: html
    path: /html
  commands:
  - rm -rf /html/dist
  - mv dist /html/

volumes:
- name: html
  host:
    path: /usr/local/soft/nginx/html/tools