when:
  - event: [manual, tag, deployment]
  - event: push
    branch: [master]
    path: [ "dist/**", ".woodpecker/*" ]

steps:
  build:
    image: alpine
    volumes:
      - /usr/local/soft/nginx/html/tools:/html
    commands:
      - rm -rf /html/dist
      - mv dist /html/
